# config.yaml

# Folder paths
raw_data_folder: "raw_data"
image_bank_folder: "image_bank"
image_folder: "images"
label_folder: "labels"
dataset_folder: "dataset"

# Split ratios
train_ratio: 0.8
validation_ratio: 0.1
test_ratio: 0.1
